### ISSUE TITLE
Bikaru is a tagged to a book-keeping language.

### ISSUE THREAD

**Issue by SimonGreenhill** [numeralbank/barlowpacific#1]
It's probably https://glottolog.org/resource/languoid/id/pika1238

**Comment by barlowrussell** [comment]
Yes, the "real" Bikaru is likely Pikaru ... but this wordlist is its own thing. Here's what the ISO change request form has to say about it: "Donald Laycock in the 1970s used a wordlist of the Pikaru dialect of Bisorio, taken during an Australian patrol by L. Bragge, and classified it as a separate language of the Sepik Hill Family. Bob Conrad and Ron Lewis went back later and took wordlists of Bikaru (which they called Pikaru, which in the Ethnologue is also listed as a dialect of Bisorio), and found that Bragge's wordlist was a poor elicitation (being only 22% cognate with the same "language" in Pikaru 1 village). ... Laycock cites a published study that shows that the wordlist the existence of the language is based on was not reliable--collected monolingually by a government patrol officer."
