### ISSUE TITLE
What the heck did I do?

### ISSUE THREAD

**Issue by barlowrussell** [numeralbank/barlowpacific#2]
I tried to make a couple of minor updates, but somehow made a bunch of changes. I think it was because I made a pull request? I'm not sure. I only made the pull request because I thought I had to in order to update my security credentials. I'm very confused, but I think that everything should be reverted to how it was before my last commit ... if possible! Help!!!

**Comment by Bibiko** [comment]
Reverting isn't that complicated, but please tell us what do mean **exactly** with "... how it was before my last commit". You mean really your last commit (out of three, see https://github.com/numeralbank/barlowpacific/commits/main ) today? Or do you mean all commits you did today (in other words back to the status of Feb 07)?

**Comment by barlowrussell** [comment]
Oh, well, now I'm even more confused. I had thought my first two commits hadn't worked ... that's why I did whatever I did for that third commit ... but now I see that they had. Those first two from today actually look good and correct. Could you please just revert back to before the third commit from today? I have no idea what happened, but somehow there were 2,206 additions and 489 deletions there. Thanks!!!

**Comment by Bibiko** [comment]
Done. Please check. If good, you can close this issue.

**Comment by barlowrussell** [comment]
Looks good! Thanks, @Bibiko !
